<a href="https://colab.research.google.com/github/Sayamm03/Skill-Code/blob/main/Class_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
file_path = '/content/drive/MyDrive/Dataset/WWTP_Dataset.csv'
df = pd.read_csv(file_path)

In [7]:
print("loaded: ", df.shape)

loaded:  (2400, 20)

In [8]:
df.head()

,timestamp,rainfall_mm,storm_event_flag,wet_dry_index,inflow_m3_hr,BOD_in,COD_in,TSS_in,TN_in,TP_in,NH4_in,aeration_rate,sludge_recirculation,chemical_dose,HRT,SRT,DO_setpoint,energy_kwh,total_operational_cost,effluent_violation_index
0,2022-01-01 00:00:00,7.181038,0,1,843.877521,297.664855,485.688948,244.743472,28.824194,13.231587,41.390928,588.907735,67.776703,18.859618,9.049146,12.548642,2.347510,371.172061,60.455855,6.533557
1,2022-01-01 01:00:00,4.483394,0,1,787.658324,414.195173,885.847933,180.130920,65.925933,4.680308,31.225490,459.490033,46.925833,28.457135,10.347552,23.156950,1.671725,317.474985,60.511498,7.729642
2,2022-01-01 02:00:00,4.146851,0,1,922.716775,273.873357,468.756012,183.693417,64.654116,7.809749,14.097685,576.832719,27.275163,29.420854,4.115909,22.375485,2.695819,351.291318,69.302074,9.380639
3,2022-01-01 03:00:00,4.146907,0,1,912.509357,311.248126,872.061495,371.518411,74.200461,3.903091,38.390691,273.644568,53.544064,29.883558,11.042915,14.850837,1.554417,171.741570,47.878015,7.195235
4,2022-01-01 04:00:00,13.949143,1,1,1562.286176,247.184848,531.402865,329.163547,20.509161,9.542533,24.513149,508.431473,35.902612,21.734778,11.632398,8.520426,2.758477,366.995112,77.995356,4.605449

In [9]:
df.tail()

,timestamp,rainfall_mm,storm_event_flag,wet_dry_index,inflow_m3_hr,BOD_in,COD_in,TSS_in,TN_in,TP_in,NH4_in,aeration_rate,sludge_recirculation,chemical_dose,HRT,SRT,DO_setpoint,energy_kwh,total_operational_cost,effluent_violation_index
2395,2022-04-10 19:00:00,16.978483,1,1,1363.243669,341.362900,615.249716,449.151788,56.573649,4.051709,25.255507,597.299213,58.846286,17.125518,6.761369,22.025407,2.587016,378.846720,68.807860,8.808606
2396,2022-04-10 20:00:00,10.113793,1,1,1647.627656,550.892211,1321.946180,455.466158,60.904157,8.184055,23.885624,453.068891,53.622576,14.025552,5.486563,14.231528,1.680745,301.921326,59.339446,17.957970
2397,2022-04-10 21:00:00,4.818769,0,1,787.159786,422.410463,408.583838,146.578724,50.332503,6.850381,43.654384,638.300101,50.398955,16.872283,11.536202,11.152669,2.429022,425.190846,64.304084,6.697230
2398,2022-04-10 22:00:00,1.034662,0,0,529.606853,220.706134,778.355415,279.259933,61.653913,11.478730,11.412090,634.506821,59.006782,26.216767,7.690123,19.484072,1.855278,389.839132,60.665275,7.452849
2399,2022-04-10 23:00:00,0.533326,0,0,489.477532,422.477566,574.188216,341.542464,30.365279,13.442900,48.989478,578.898970,65.292533,29.760792,7.337936,9.338935,1.922383,372.419491,59.257578,9.533993

In [10]:
df.describe()

,rainfall_mm,storm_event_flag,wet_dry_index,inflow_m3_hr,BOD_in,COD_in,TSS_in,TN_in,TP_in,NH4_in,aeration_rate,sludge_recirculation,chemical_dose,HRT,SRT,DO_setpoint,energy_kwh,total_operational_cost,effluent_violation_index
count,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000
mean,6.104493,0.163750,0.750000,868.090365,321.982769,662.466132,308.489707,50.415856,9.121099,30.443030,505.996502,49.701750,17.100766,8.030954,16.473147,2.487444,321.305035,53.309234,8.638752
std,4.232492,0.370126,0.433103,321.981270,109.167110,237.638128,110.691026,17.273364,3.453742,11.625557,171.793331,17.124289,7.113718,2.331385,4.863755,0.575733,105.687666,15.545235,2.773752
min,0.077581,0.000000,0.000000,450.040154,150.015848,300.094647,120.501550,20.015147,3.007340,10.001925,200.305993,20.006614,5.003128,4.000540,8.000094,1.500360,106.798589,18.099686,3.255297
25%,3.001297,0.000000,0.750000,711.314017,236.838450,483.503690,210.223484,35.587115,6.228560,20.480249,356.308213,35.114551,10.901861,6.015137,12.181433,1.981000,233.147718,41.258261,6.652015
50%,5.175488,0.000000,1.000000,835.726341,310.363975,639.362762,305.875025,51.016197,9.110944,30.814780,506.532452,49.833015,17.044623,7.993479,16.594567,2.485394,321.747744,52.829867,8.143528
75%,8.079237,0.000000,1.000000,907.475448,393.133064,802.058474,408.051299,65.157569,11.998074,40.636512,652.716351,64.100610,22.958329,10.117882,20.511485,2.978690,409.475937,64.514689,10.135899
max,40.830698,1.000000,1.000000,1649.762190,674.289555,1439.686277,499.925955,79.995490,14.998457,49.996039,799.670314,79.975903,29.992390,11.997857,24.996419,3.498481,541.093190,102.819987,20.865681

In [14]:
print("Missing value per column:\n", df.isnull().sum(), sep="")

Missing value per column:
timestamp                   0
rainfall_mm                 0
storm_event_flag            0
wet_dry_index               0
inflow_m3_hr                0
BOD_in                      0
COD_in                      0
TSS_in                      0
TN_in                       0
TP_in                       0
NH4_in                      0
aeration_rate               0
sludge_recirculation        0
chemical_dose               0
HRT                         0
SRT                         0
DO_setpoint                 0
energy_kwh                  0
total_operational_cost      0
effluent_violation_index    0
dtype: int64